import type { ComponentType } from "react";
import type { LucideProps } from "lucide-react-native";
import {
  Sparkles,
  SprayCan,
  CookingPot,
  Utensils,
  ShoppingCart,
  Droplet,
  Shirt,
  Dog,
  Cat,
  Flower2,
  Trash2,
  Wrench,
  Hammer,
  Paintbrush,
  Bed,
  Bath,
  Car,
  Bike,
  Dumbbell,
  Pill,
  Heart,
  Baby,
  BookOpen,
  Mail,
  Phone,
  Wifi,
  Zap,
  Thermometer,
  Fan,
  Refrigerator,
  WashingMachine,
  Lamp,
  Key,
  Package,
  Recycle,
  Leaf,
} from "lucide-react-native";

/** Icon name map for routine tasks — used with lucide-react-native */
export const TASK_ICON_NAMES = [
  "sparkles",
  "spray-can",
  "cooking-pot",
  "utensils",
  "shopping-cart",
  "droplet",
  "shirt",
  "dog",
  "cat",
  "flower-2",
  "trash-2",
  "wrench",
  "hammer",
  "paintbrush",
  "bed",
  "bath",
  "car",
  "bike",
  "dumbbell",
  "pill",
  "heart",
  "baby",
  "book-open",
  "mail",
  "phone",
  "wifi",
  "zap",
  "thermometer",
  "fan",
  "refrigerator",
  "washing-machine",
  "lamp",
  "key",
  "package",
  "recycle",
  "leaf",
] as const;

export type TaskIconName = (typeof TASK_ICON_NAMES)[number];

const TASK_ICON_MAP: Record<TaskIconName, ComponentType<LucideProps>> = {
  "sparkles": Sparkles,
  "spray-can": SprayCan,
  "cooking-pot": CookingPot,
  "utensils": Utensils,
  "shopping-cart": ShoppingCart,
  "droplet": Droplet,
  "shirt": Shirt,
  "dog": Dog,
  "cat": Cat,
  "flower-2": Flower2,
  "trash-2": Trash2,
  "wrench": Wrench,
  "hammer": Hammer,
  "paintbrush": Paintbrush,
  "bed": Bed,
  "bath": Bath,
  "car": Car,
  "bike": Bike,
  "dumbbell": Dumbbell,
  "pill": Pill,
  "heart": Heart,
  "baby": Baby,
  "book-open": BookOpen,
  "mail": Mail,
  "phone": Phone,
  "wifi": Wifi,
  "zap": Zap,
  "thermometer": Thermometer,
  "fan": Fan,
  "refrigerator": Refrigerator,
  "washing-machine": WashingMachine,
  "lamp": Lamp,
  "key": Key,
  "package": Package,
  "recycle": Recycle,
  "leaf": Leaf,
};

export function getTaskIcon(name: string | null): ComponentType<LucideProps> {
  if (!name) return Sparkles;
  return TASK_ICON_MAP[name as TaskIconName] ?? Sparkles;
}
